In [1]:
import polynomial

In [8]:
import numpy as np

In [102]:
class Polynomial():

    def __init__(self, coef=[0]):
        self.coef = np.array(coef)
        self.exp = self._determine_exponents()
        pass

    def _determine_exponents(self):
        # Create list of exponents based on size of array
        return np.array(range(len(self.coef)-1,-1,-1))

    def result(self,x):
        # calculates y for the polynomail funciton given x
        return np.power(np.array(self.coef)*x,self.exp).sum()

    def __repr__(self):
        rep_str = "Polynomial: "
        for i in range(len(self.coef)):
            if self.exp[i] > 0:
                rep_str += str(self.coef[i])+'x^'+str(self.exp[i])+ ' + '
            else:
                rep_str += str(self.coef[i])
        return rep_str

    

In [148]:
class Derivative(Polynomial):

    def __init__(self, coef=[0],order=1):
        Polynomial.__init__(self,coef)
        self.dcoef = self.coef
        self.dexp = self._determine_exponents()
        self.order = order
        if order > self.exp[0]:
            print('Warning: Order larger than the polynomial')
        self.derivate(order)

    def derivate(self,order):
        for i in range(1,order+1):
            self.dcoef = np.multiply(self.dcoef,self.dexp)[:-1]
            self.dexp = self.dexp[:-1]-1
    
    def __repr__(self):
        rep_str = "Polynomial: "
        der_str = "Order " + str(self.order) + " Derivative: "
        for i in range(len(self.coef)):
            if self.exp[i] > 0:
                rep_str += str(self.coef[i])+'x^'+str(self.exp[i])+ ' + '
            else:
                rep_str += str(self.coef[i])
        for i in range(len(self.dcoef)):
            if self.dexp[i] > 0:
                der_str += str(self.dcoef[i])+'x^'+str(self.dexp[i])+ ' + '
            else:
                der_str += str(self.dcoef[i])
        return rep_str +' \n' + der_str


In [149]:
poly = Polynomial([1,2,3,4,5])

In [150]:
poly

Polynomial: 1x^4 + 2x^3 + 3x^2 + 4x^1 + 5

In [151]:
poly.exp

array([4, 3, 2, 1, 0])

In [152]:
poly.coef

array([1, 2, 3, 4, 5])

In [153]:
poly.result(5)

1871

In [154]:
polyD = Derivative([1,2,3,4,5],order=2)
polyD

Polynomial: 1x^4 + 2x^3 + 3x^2 + 4x^1 + 5 
Order 2 Derivative: 12x^2 + 12x^1 + 6

In [88]:
for i in range(1,order+1):
    print(i)

1


In [91]:
poly.coef

array([1, 2, 3, 4, 5])

In [92]:
poly.exp

array([4, 3, 2, 1, 0])

In [96]:
string = ''
for i in range(len(poly.coef)):
    if poly.exp[i] > 0:
        string += str(poly.coef[i])+'x^'+str(poly.exp[i])+ ' + '
    else:
        string += str(poly.coef[i])

In [97]:
string

'1x^4 + 2x^3 + 3x^2 + 4x^1 + 5'